immuni-app/immuni-app-ios

App/Application/AppDelegate.swift
App/Dependencies/AppDependencies+DebugMenu.swift
App/Logic/LifecycleLogic.swift
App/Logic/SharedLogic.swift
App/State/EnvironmentState.swift

This PR removes the `today` variable from the app state, that, as a consequence of #12, is not anymore used.
- remove today variable
- remove lifecycle logic that handled the var updates
In particular, the ...
Check diff after merge of #12.

feat: remove today var

---

App/UI/Privacy/PrivacyVC.swift
App/UI/Privacy/PrivacyView.swift

Fixes the calculated coordinates offset for the cell containing the privacy checkmarks.
The view doesn't scroll appropriately (on iPhone 11 and similar devices).
- Fixes privacy view scroll position
In particular, the ...
- Exposes the `scrollableGradientView` instance to other classes.
- To calculate checkmark cell visibility we consider its bottom position (not top) and that part of the collection view is covered by the aforementioned `scrollableGradientView`.
- Fixes #11

fix: privacy view not scrolling

---

Modules/Networking/Core/NetworkManager.swift

Backend error codes did change.
`400 | 1102 | Province is invalid.` dropped and fallback to `400 | 1002 | Request not compliant with the defined schema.`
`401 | 1103 | Unauthorised OTP.` code changed from `1103` to `1102`

fix: update error codes

---

App/Application/AppDelegate.swift
App/Application/AppNavigation.swift
App/Logic/LifecycleLogic.swift
App/Logic/SharedLogic.swift
App/UI/Onboarding/OnboardingContainer/OnboardingContainerNC.swift
App/UI/SensitiveDataCover/SensitiveDataCover.swift

This PR adds a blur cover to the app's screen when the app becomes inactive / goes to background.
This is done to avoid a possible low-level malware to access the screenshots that are stored by the OS to implement the multi-tasking functionality. 
- Fixes #21
No UITests are added for the new vc as it's just a UIVisualEffectView with a blur effect. Consider to add them if the view becomes more complex.

feat: hide sensitive data cover

---

App/Dependencies/ExposureDetection/ImmuniFileStorage.swift
Podfile
Podfile.lock
README.md

The PR changes the Zip library. ZipFoundation uses Apple's methods behind scenes
more info here https://github.com/weichsel/ZIPFoundation

feat: move from ssziparchive to zipfoundation

---

App/Logic/PermissionTutorialLogic.swift
App/UI/Home/HomeVC.swift
App/UI/Onboarding/Permission/OnboardingPermissionVC.swift
App/UI/PermissionTutorial/PermissionTutorialVM.swift
App/UI/Welcome/WelcomeVC.swift
UITests/PermissionTutorial/PermissionTutorialUITests.swift

This PR adds the CTA button in the `How it works` screen only when needed.
According to the product team the CTA button that brings to FAQ should be visible only when the screen is presented from the Home tab.
- Addresses #35

feat: how it works cta

---

App/Logic/DataUploadLogic.swift
App/Logic/SharedLogic.swift
App/Resources/de.lproj/Localizable.strings
App/Resources/en-GB.lproj/Localizable.strings
App/Resources/it.lproj/Localizable.strings
App/UI/Onboarding/PermissionOverlay/OnboardingPermissionOverlayVM.swift
UITests/Onboarding/OnboardingPermissionOverlayUITests.swift

This PR fixes the hint in the permission overlay in the data upload process.
Formally, it adds a copy to select the `Condividi` button in the diagnosis keys fetch authorization alert.
Also it fixes an issue when presenting the permission overlay screen to avoid to cover the screen with `SensitiveDataOverlayVC`.

feat: diagnosis key permission overlay

---

App/Dependencies/AppDependencies+DebugMenu.swift
App/Logic/DataUploadLogic+DummyTraffic.swift
App/Logic/DataUploadLogic.swift
AppTests/Networking/FixedSizeJsonRequestTests.swift
Modules/Extensions/String+Utils.swift
Modules/Models/Configuration.swift
Modules/Networking/Core/FixedSizeJSONRequest.swift
Modules/Networking/Core/NetworkManager.swift
Modules/Networking/Helpers/JSONRequest+EmptyBody.swift
Modules/Networking/Requests/DataUploadRequest.swift
Modules/Networking/Requests/DummyIngestionRequest.swift
Modules/Networking/Requests/OTPValidationRequest.swift

*Note*: Merge after #57 
This PR implements the necessary logic to ensure all Ingestion requests have the same apparent size (when considering URL + Method + Headers + Body).
See [the technical document]https://github.com/immuni-app/immuni-documentation/blob/master/Traffic%20Analysis%20Mitigation.md) for more information.

feat: ensure all ingestion requests have the same size

---

.circleci/config.yml

This PR makes so that the DEV Tools are not included in CI production builds, but are included in CI development builds.

ci: disable tooling for production builds only

---

App/Dependencies/ExposureDetection/ImmuniExposureDetectionExecutor.swift
AppTests/App/Logic/ExposureDetectionLogicTests.swift
AppTests/ImmuniExposureNotification/ExposureNotificationMocks.swift
Modules/ImmuniExposureNotification/ENConformances/ENTypes+Bridging.swift
Modules/ImmuniExposureNotification/ExposureNotification+Models.swift
Modules/ImmuniExposureNotification/FallbackStubs/ExposureNotificationProviderStub.swift
Modules/Models/Configuration.swift

This PR aligns the configuration properties and defaults to the backend. Moreover, it wires the [attenuationDurationThresholds](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586322-metadata) of ENExposureConfiguration, although from what I'm seeing it seems that the framework currently discards it and defaults to `[50, 70]`.

fix: align configuration properties and defaults

---

App/Application/AppDelegate.swift
App/Logic/LifecycleLogic.swift
AppTests/App/Logic/DataUploadLogicTests.swift
AppTests/App/Logic/ExposureDetectionLogicTests.swift
Modules/Models/Configuration.swift

This PR fixes the lifecycle logic to only perform certain actions when OnStart is called in a foreground session.
Also, moves a sideeffect from WillResignActive to DidEnterForeground

fix: lifecycle management

---

App/Logic/SettingsLogic.swift
App/State/FaqState.swift
App/UI/Privacy/Cells/PrivacyCheckboxCell.swift
App/UI/Privacy/Cells/PrivacyTOUCell.swift
App/UI/Privacy/PrivacyVC.swift
App/UI/Privacy/PrivacyVM.swift
App/UI/Privacy/PrivacyView.swift
App/UI/Settings/SettingsVC.swift
AppTests/App/Logic/AppSetupLogicTests.swift
AppTests/App/Logic/ExposureDetectionLogicTests.swift
Makefile
Modules/Models/Configuration.swift
Modules/Models/FAQ.swift
Modules/Models/UserLanguage.swift
UITests/Onboarding/PrivacyUITests.swift

This PR fixes the naming of the TOS (now TOU) and Privacy Policy (now Privacy Notice) and introduces missing languages

fix: configuration naming

---

dangerfile.ts

This PR adds two checks for danger:
- when a pr is toward master, but the branch is not a release one, an error is shown
- when a or is toward master and the branch is a release one, a warning is added

chore: add danger checks for branches

---

App/Logic/CovidStatusLogic.swift

This PR removes the first risk notification, which is already delivered by iOS when a full detection is performed.
- Addresses #80

fix: remove repeated risk notification

---

.circleci/config.yml

This PR improves the execution of PR checks on forked PRs. 
In the previous implementation of the scheduler system, PR checks on forked PRs were executed by identifying _unauthorised_ workflows and scheduling a re-run with the necessary settings to run Danger. However, due to limitations of CircleCI, such workflows may not be unauthorised in the first place, or may not have access to the necessary settings even after they're re-scheduled. This may result in Danger checks not being run on certain forked PRs, which limits our ability to maintain a consistent coding style and give constructive feedbacks to the community.
To solve this issue, we propose a different approach in which Danger is executed directly by the scheduler workflow for all forked PRs, regardless of the authorisation …

[WIP] [FEAT] Enable danger on forked PRs within scheduler

---

App/Dependencies/ExposureDetection/ImmuniExposureDetectionExecutor.swift
App/Logic/ExposureDetectionLogic.swift
AppTests/App/Dependencies/ImmuniExposureDetectionExecutorTests.swift
AppTests/ImmuniExposureNotification/ExposureNotificationMocks.swift
Modules/ImmuniExposureNotification/ExposureDetectionExecutor.swift
Modules/Models/Configuration.swift
Modules/Models/CovidStatus/CovidStatus.swift

When a user is positive, the app shouldn't send any additional notification. While the app's logic already does that, it sometimes accesses to the EN manager to retrieve the Exposure Info. This triggers an automatic notification that we cannot prevent. This PR prevents the logic from accessing Exposure Info when a user is positive.

feat: prevent the app from accessing exposure info

---

App/UI/Privacy/PrivacyVC.swift
App/UI/Privacy/PrivacyView.swift
Modules/Models/FAQ.swift

This PR adds a fix to voice over experience when user does not toggle checkboxes in privacy view.

feat: improve accessibility

---

App/UI/Home/HomeView.swift
App/UI/Settings/SettingsView.swift
App/UI/Suggestions/Cells/SuggestionsHeaderCell.swift
App/UI/Suggestions/SuggestionView.swift

This PR fixes a couple of UI issue related to collections.
- an issue with the suggestions header when `UIContentSizeCategory` is set to `small` or `extra small`
- main tabs collection content insets
- addresses #135 
- addresses #146

fix: collections ui

---

App/Dependencies/ExposureDetection/ImmuniTemporaryExposureKeyProvider.swift
AppTests/App/Dependencies/ImmuniTemporaryExposureKeyProviderTests.swift

This PR tackles a bug in which the exposure detection was not being performed in case the backend was returning only a single chunk.

fix: correctly handle case with one chunk

---

App/Logic/SharedLogic.swift
App/UI/SensitiveDataCover/SensitiveDataCover.swift

This PR makes the shield that protects the UI during the multitasking more robust.
It also fixes a glitch
Addresses https://github.com/immuni-app/immuni-app-ios/issues/191
Addresses https://github.com/immuni-app/immuni-app-ios/issues/192

feat: update cover

---

App/Logic/ExposureDetectionLogic.swift
App/Logic/LifecycleLogic.swift
Modules/PushNotification/PushNotification.swift
Modules/PushNotification/Utility/LocalNotificationScheduler.swift

This PR implements a logic that removes the "service not active" push notification once it is not longer needed

feat: remove notifications when they’re not longer needed

---

App/UI/Home/Cells/HomeServiceActiveCell.swift
App/UI/Home/HomeView.swift
Modules/Models/Configuration.swift

The PR adds the tap on the whole card in home, instead of just having the tap on "discover more"

feat: enable tap on whole card

---

App/UI/Onboarding/Advice/OnboardingAdviceView.swift
App/UI/Onboarding/Permission/OnboardingPermissionView.swift

This PR fixes an issue related to the animations in the onboarding as the intrinsicContentSize of the animations is too big to be used.
- addresses #252

fix: use static expected asset height

---

App/UI/Shared/CollectionViewLayouts/CollectionWithShadowLayout.swift

This PR fixes an issue with `CollectionWithShadowLayout` that happens for long collections in small devices as `cellForItem` can return a `nil` value when the cell is not visible.
- addresses #253

feat: cache decorated cell paths

---

App/UI/Settings/Cells/SettingCell.swift
App/UI/Settings/CustomerSupport/Cells/CustomerSupportInfoCell.swift
App/UI/Settings/CustomerSupport/CustomerSupportView.swift
App/UI/Settings/SettingsView.swift
App/UI/Shared/CollectionViewLayouts/CollectionWithShadowLayout.swift

This PR moves the calculation of cell with shadow from cells to their view models.
The rationale behind is that the cells of a collection view can be nil while not visible when `cellForItem` is evaluated. By moving the calculation as an evaluation of their view models, possible issues with the index paths are avoided.
- addresses: #285

fix: improve collection with shadow

---

project.yml

This PR introduces the two plist entries required for iOS 14.
https://developer.apple.com/documentation/bundleresources/information_property_list/enapiversion?changes=latest_minor
https://developer.apple.com/documentation/bundleresources/information_property_list/endeveloperregion?changes=latest_minor

chore: add iOS 14 plist entries

---

App/Logic/CovidStatusLogic.swift
App/Logic/LifecycleLogic.swift

This PR fixes the removal of the risk repeating notifications.
The problem was that
* when the app was killed
* when the app was launched from a notification
the `onStart` was called when the `UIApplication.State` was `inactive`. The check failed to pass and the notification wasn't removed.
The fix consists in switching the check, ensuring that `it is not in background` rather than `being active`. When the app is launched in background, it doesn't pass from inactive to background, but goes in background directly.
Reference https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle
`Respond to App-Based Life-Cycle Events` chapter

fix: properly remove notifications on launch
