- README.md
Fixed wrong folder name in installation instructions
> fix: correct installation instructions of README.md

- AppTests/App/Logic/DataUploadLogicTests.swift
Removes an outdated warning from the codebase
No issue tracked
> chore: remove outdated warning

- README.md
Add CI badge so it's possible to glance over the readme to check the build status of the app.
> feat: add CI badge.

- README.md
There are some spelling and grammar issues on the README.md
- Fixes 3 grammar or spelling issues in the document
Note that I haven't opened an issue as this is a trivial change.
> docs: Improve grammar and spelling in README.md

- App/Logic/DataUploadLogic.swift
Fix a typo to make the app compile.
> fix: compilation error

- Modules/Networking/Helpers/HTTPHeader+Custom.swift
- Modules/Networking/Requests/AnalyticsRequest.swift
- Modules/Networking/Requests/ConfigurationRequest.swift
- Modules/Networking/Requests/DataUploadRequest.swift
- Modules/Networking/Requests/DownloadKeyChunkRequest.swift
- Modules/Networking/Requests/FAQRequests.swift
- Modules/Networking/Requests/KeysIndexRequest.swift
- Modules/Networking/Requests/OTPValidationRequest.swift
This PR:
- changes the default headers to make them consistent across all the network calls
- prevent the OS from caching useless network calls
> [FEAT] Improve network calls

- App/Logic/ExposureDetectionLogic.swift
- App/Logic/LifecycleLogic.swift
- Modules/Models/FAQ.swift
- UITests/FAQ/FaqUITests.swift
- UITests/FAQ/QuestionUITests.swift
This PR adds the latest version of the FAQ in Italian and English.
> feat: add default faq

- App/Logic/DataUploadLogic.swift
- Modules/Networking/Core/NetworkManager.swift
This PR updates the error code to the latest version.
> feat: update backend error codes

- App/Resources/de.lproj/Localizable.strings
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
This PR updates some copy in the app.
- Addresses #55
- Addresses #46
> feat: update copy

- App/Style/TextStyles.swift
- App/UI/Onboarding/Advice/OnboardingAdviceView.swift
- App/UI/Settings/SettingsView.swift
- App/UI/Suggestions/Cells/SuggestionsButtonCell.swift
- App/UI/Suggestions/SuggestionsVM.swift
This PR adds minor fixes to the design.
> feat: improve design

- Modules/Extensions/Data+Utils.swift
This PR fixes a bug in the implementation of `Data.random(with:)`.
> fix: generate more than 10 bytes of randomness

- Modules/Models/Configuration.swift
This PR adds final PP and TOS links
> feat: add final PP and TOS links

- Modules/Models/FAQ.swift
This PR updates the English FAQs.
> feat: update EN FAQs

- Modules/Models/Configuration.swift
This PR fixes PP and TOS links previously introduced
> fix: tos and pp links

- App/Logic/DataUploadLogic.swift
This PR updates the copy for the connection error for ingestion requests as discussed with the product team.
> fix: connection error copy

- App/Resources/Entitlements/Development.entitlements
This entitlement is not necessary anymore for development, and it's better to be aware asap, should the file signing break.
> fix: remove skip signing entitlement

- Modules/Models/Configuration.swift
This PR tunes the default values for the configuration
> fix: user correct configuration default values

- Makefile
- Modules/Extensions/Bundle+CommonKeys.swift
- project.yml
This PR removes the unused email from the project
> fix: remove unused email

- App/Dependencies/ImmuniSessionProvider.swift
- App/UI/Web/WebView.swift
This PR prevents the web view from loading not authorized URLs
> fix: prevent from loading non authorized urls

- App/Resources/de.lproj/Localizable.strings
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/es-ES.lproj/Localizable.strings
- App/Resources/fr.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
- App/UI/Privacy/Cells/PrivacyCheckboxCell.swift
- App/UI/Suggestions/Cells/SuggestionsButtonCell.swift
This PR fixes some copy and localization issues.
> fix: localization issues

- App/Application/AppNavigation.swift
- App/Logic/LifecycleLogic.swift
- App/Logic/OnboardingLogic.swift
- App/Resources/en-GB.lproj/Localizable.strings
- App/UI/Confirmation/ConfirmationVC.swift
- App/UI/Onboarding/Advice/OnboardingAdviceVC.swift
- App/UI/Onboarding/OnboardingContainer/OnboardingContainerAccessoryView.swift
- App/UI/Onboarding/OnboardingContainer/OnboardingContainerNC.swift
- App/UI/Onboarding/Permission/OnboardingPermissionVC.swift
- App/UI/Onboarding/Province/OnboardingProvinceVC.swift
- App/UI/Onboarding/Region/OnboardingRegionVC.swift
- AppTests/App/Logic/OnboardingLogicTests.swift
- UITests/Onboarding/OnboardingAdviceUITests.swift
- UITests/Onboarding/OnboardingPermissionsUITests.swift
- UITests/Onboarding/OnboardingProvinceUITests.swift
- UITests/Onboarding/OnboardingRegionUITests.swift
This PR improves the UI and UX behaviour and adds some redundant check to improve robustness.
> feat: improve ui robustness

- App/UI/Privacy/Cells/PrivacyCheckboxCell.swift
This PR fixes an issue with the privacy checkbox cell layout
> fix: privacy checkbox layout

- Modules/Models/FAQ.swift
> feat: update faq

- App/Resources/en-GB.lproj/Localizable.strings
- App/UI/TabBar/TabbarVC.swift
This PR improves some UX flaws related to tabbar.
In particoular it adds:
- pop of view controller when tapping on settings tabbar item if possible
- properly update of font size on not selected tab
- addresses #124 
- addresses #129
> fix: tabbar interactions

- App/Logic/LifecycleLogic.swift
- Modules/Models/FAQ.swift
This PR updates the default values for Italian and English FAQs.
> fix: update default faqs

- Modules/Models/FAQ.swift
> feat: add faq

- App/Resources/es-ES.lproj/Localizable.strings
> fix: es copy

- Modules/Models/FAQ.swift
> feat: update FAQs

- Modules/Models/FAQ.swift
This PR updates the default FAQs.
> fix: update faqs

- Modules/Models/FAQ.swift
> feat: add one FAQ

- App/Resources/it.lproj/Localizable.strings
Adds new strings for the upcoming UI changes
> feat: add new strings

- App/Logic/SharedLogic.swift
- App/Resources/it.lproj/Localizable.strings
- App/UI/Suggestions/Cells/SuggestionsMessageCell.swift
- App/UI/Suggestions/SuggestionView.swift
- App/UI/Suggestions/SuggestionsVC.swift
- App/UI/Suggestions/SuggestionsVM.swift
- swiftgen.yml
This PR updates the suggestions' design and adds a privacy notice to the bottom the page
> feat: update suggestions

- Modules/Models/Configuration.swift
This PR updates the default settings of the app
> feat: update default settings

- App/Logic/OnboardingLogic.swift
- AppTests/App/Logic/OnboardingLogicTests.swift
- Modules/Models/Configuration.swift
- UITests/Suggestions/SuggestionsUITests.swift
This PR plugs the configuration to show/hide the pilot page
> feat: plug configuration

- App/UI/TabBar/TabbarCell.swift
- App/UI/TabBar/TabbarView.swift
This PR improves the VoiceOver usage of the app by adding the tabbar accessibility traits.
> feat: add tabbar accessibility traits

- Modules/ImmuniExposureNotification/ENConformances/ENManager+ExposureNotificationProvider.swift
Fixes the TEKs retrieval when the app runs in TF, but with debug menu activated
> fix: improve handling of TF builds with dbug menu

- Podfile
- Podfile.lock
Updates the dependencies to the last version
> chore: update dependencies

- App/Application/AppNavigation.swift
- App/Logic/SettingsLogic.swift
- App/Logic/SharedLogic.swift
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
- App/UI/Settings/CustomerSupport/CustomerSupportVC.swift
- App/UI/Settings/CustomerSupport/CustomerSupportVM.swift
- App/UI/Settings/CustomerSupport/CustomerSupportView.swift
- App/UI/Settings/MailComposer/MailComposer.swift
This PR adds the interactions in the customer support screen. See #200.
> feat: customer support interactions

- App/Application/AppNavigation.swift
- App/Dependencies/AppDependencies.swift
- App/Logic/SettingsLogic.swift
- App/Logic/SharedLogic.swift
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
- App/UI/Settings/CustomerSupport/CustomerSupportVC.swift
- App/UI/Settings/CustomerSupport/CustomerSupportVM.swift
- App/UI/Settings/CustomerSupport/CustomerSupportView.swift
- App/UI/Settings/MailComposer/MailComposer.swift
- AppTests/Helpers/MockAppDependencies.swift
- UITests/CustomerSupport/CustomerSupportUITests.swift
This PR adds the uitests for the customer support screen. See #200.
> feat: customer support tests

- App/State/AppState.swift
This PR fixes the configuration persistance
> fix: persist configuration

- App/Application/AppNavigation.swift
- App/Dependencies/AppDependencies.swift
- App/Logic/SettingsLogic.swift
- App/State/AppState.swift
- App/UI/Settings/CustomerSupport/Cells/CustomerSupportContactCell.swift
- App/UI/Settings/CustomerSupport/Cells/CustomerSupportInfoCell.swift
- App/UI/Settings/CustomerSupport/CustomerSupportVM.swift
- App/UI/Settings/CustomerSupport/CustomerSupportView.swift
- AppTests/Helpers/MockAppDependencies.swift
- UITests/CustomerSupport/CustomerSupportUITests.swift
This PR handles accessibility and voice over in the customer support screen. See #200.
> feat: customer support accessibility

- App/Resources/de.lproj/Localizable.strings
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/es-ES.lproj/Localizable.strings
- App/Resources/fr.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
This PR updates the copy on the Load Data section of the settings.
> fix: update load data copy

- App/Logic/PermissionTutorialLogic.swift
- App/Resources/it.lproj/Localizable.strings
- App/UI/Home/Cells/HomeServiceActiveCell.swift
- App/UI/Home/HomeVC.swift
- App/UI/Home/HomeView.swift
- App/UI/PermissionTutorial/PermissionTutorialVM.swift
- UITests/AppSetup/AppSetupUITests.swift
- UITests/Confirmation/ConfirmationUITests.swift
- UITests/CustomerSupport/CustomerSupportUITests.swift
- UITests/FAQ/FaqUITests.swift
- UITests/FAQ/QuestionUITests.swift
- UITests/ForceUpdate/ForceUpdateUITests.swift
- UITests/Home/HomeUITests.swift
- UITests/Onboarding/OnboardingAdviceUITests.swift
- UITests/Onboarding/OnboardingPermissionOverlayUITests.swift
- UITests/Onboarding/OnboardingPermissionsUITests.swift
- UITests/Onboarding/OnboardingProvinceUITests.swift
- UITests/Onboarding/OnboardingRegionUITests.swift
- UITests/Onboarding/PrivacyUITests.swift
- UITests/PermissionTutorial/PermissionTutorialUITests.swift
- UITests/Settings/SettingsUITests.swift
- UITests/Settings/SettingsUpdateProvinceUITests.swift
- UITests/Settings/SettingsUpdateRegionUITests.swift
- UITests/Suggestions/SuggestionsUITests.swift
- UITests/UploadData/ConfirmUploadUITests.swift
- UITests/UploadData/UploadDataUITests.swift
- UITests/Welcome/WelcomeUITests.swift
This PR adds a new piece of UI that explains to users how to verify that Immuni is working.
> feat: Add explaination about whether Immuni is working

- App/UI/Onboarding/Region/OnboardingRegionVM.swift
- App/UI/Onboarding/Region/OnboardingRegionView.swift
- Modules/Models/Region.swift
This PR adds alternative versions of the region/province names
> feat: add alternate version of province/region

- App/Resources/it.lproj/Localizable.strings
- App/UI/Welcome/WelcomeView.swift
This PR improves the welcome view by making it more clear which is the scrollable part
> feat: polish welcome view

- App/Logic/PermissionTutorialLogic.swift
- App/Resources/it.lproj/Localizable.strings
- App/UI/Onboarding/Province/OnboardingProvinceVC.swift
- App/UI/Onboarding/Province/OnboardingProvinceVM.swift
- App/UI/Onboarding/Province/OnboardingProvinceView.swift
- App/UI/Onboarding/Region/OnboardingRegionVC.swift
- App/UI/Onboarding/Region/OnboardingRegionVM.swift
- App/UI/Onboarding/Region/OnboardingRegionView.swift
- App/UI/Onboarding/Shared/OnboardingHeaderCell.swift
- App/UI/PermissionTutorial/PermissionTutorialVM.swift
- UITests/PermissionTutorial/PermissionTutorialUITests.swift
This PR adds Province/Region explanation during the onboarding
> feat: add Province/Region explaination

- App/Application/AppNavigation.swift
- App/Logic/OnboardingLogic.swift
- App/Resources/it.lproj/Localizable.strings
- App/UI/Onboarding/OnboardingContainer/OnboardingContainerNC.swift
- App/UI/Onboarding/Region/OnboardingRegionVM.swift
- App/UI/Onboarding/Region/OnboardingRegionView.swift
- Modules/Models/Region.swift
This PR adds the support for people that live "Abroad".
To minimize the migration issues, the abroad is managed as a special province/region
> feat: Add abroad support

- App/UI/Home/HomeVM.swift
The PR changes the order of the home's items
> feat: swap suggestions and how it work

- App/Logic/SettingsLogic.swift
- App/Resources/it.lproj/Localizable.strings
- App/State/ExposureDetectionState.swift
- App/UI/Settings/CustomerSupport/CustomerSupportVM.swift
- UITests/CustomerSupport/CustomerSupportUITests.swift
This PR introduces a new information in the CS system: the last EN check.
> feat: add customer support info

- App/UI/Welcome/WelcomePageView.swift
- App/UI/Welcome/WelcomeView.swift
This PR improves performances in welcome view by playing one animation per time in the welcome carousel.
- addresses #249
> feat: welcome animations performances

- App/Logic/SettingsLogic.swift
- App/UI/FAQ/FaqView.swift
- App/UI/Shared/SearchBar.swift
This PR fixes a few issues spotted by QA
- Addresses https://github.com/immuni-app/immuni-app-ios/issues/265 https://github.com/immuni-app/immuni-app-ios/issues/264 https://github.com/immuni-app/immuni-app-ios/issues/258
> fix: QA issues

- App/Resources/de.lproj/Localizable.strings
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/es-ES.lproj/Localizable.strings
- App/Resources/fr.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
This PR adds the new copies' translations
> feat: add translated copy

- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
- App/UI/Home/HomeVM.swift
- App/UI/Shared/SearchBar.swift
- App/UI/Suggestions/SuggestionsVM.swift
- App/UI/Welcome/WelcomeView.swift
- UITests/Home/HomeUITests.swift
This PR fixes some issues related to UX.
- addresses #272, #274, #275
> fix: improve ux

- App/UI/Shared/SearchBar.swift
This PR fixes a glitch in the FAQ search
Addresses https://github.com/immuni-app/immuni-app-ios/issues/281
> fix: cancel search handling

- App/UI/Onboarding/Permission/OnboardingPermissionView.swift
- App/UI/Settings/SettingsView.swift
Addresses https://github.com/immuni-app/immuni-app-ios/issues/286
> fix: ellipses on long texts

- AUTHORS
- CODEOWNERS
This PR removes Bending Spoons from the owners of the code
> docs: remove Bending Spoons from codeowners

- App/Resources/de.lproj/Localizable.strings
- App/Resources/en-GB.lproj/Localizable.strings
- App/Resources/es-ES.lproj/Localizable.strings
- App/Resources/fr.lproj/Localizable.strings
- App/Resources/it.lproj/Localizable.strings
This PR reverts the copy of the app, as it is not needed to open the app once per day
> [Revert] "fix: notifications (#324)"

- Modules/Models/Configuration.swift
- Added Croatia
- Changed in italian Olanda -> Paesi Bassi
> fix: default config country
